name: GitHub Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches: ["main", "master"]

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Metrics embed
        uses: lowlighter/metrics@v3.34
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: github-metrics.svg
          
          # 🗃️ Base profile data
          base: header, activity, community, repositories, metadata
          
          # 👨‍💻 Lines of Code Changed
          plugin_lines: yes
          plugin_lines_history_limit: 1
          plugin_lines_repositories_limit: 4
          plugin_lines_sections: base
          
          # 🤹 Most used programming languages
          plugin_languages: yes
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_details: bytes-size, percentage
          
          # 📅 3D Isometric Commit Calendar
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          
          # 🏷️ Repository Tech Topics
          plugin_topics: yes
          plugin_topics_sort: stars
          plugin_topics_limit: 15
          
          # DISABLED DUE TO GITHUB API BREAKING CHANGES:
          plugin_habits: no
          plugin_achievements: no
